name: Generate and Publish HTML

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 6 * * *'  # Optional: run daily at 6:00 UTC
  workflow_dispatch:      # Optional: allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate HTML
        run: python generate_comparison_table.py

      - name: Move HTML to docs/
        run: |
          mkdir -p docs
          mv bilbasen_comparison_table.html docs/

      - name: Commit and push HTML
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add docs/
          git commit -m "Update comparison table [skip ci]" || echo "No changes to commit"
          git push