name: Scrape Bilbasen and Publish JSON

on:
  # schedule:
  #   - cron: '0 6 * * *'  # Runs every day at 6:00 UTC
  workflow_dispatch:      # Allows manual trigger

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # Alternative: use a Personal Access Token if GITHUB_TOKEN doesn't work
          # token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python get_cars.py

      - name: Move JSON to docs/
        run: |
          mkdir -p docs
          cp data/bilbasen_cars_*.json docs/

      - name: Commit and push JSON
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add docs/
          git commit -m "Update scraped data [skip ci]" || echo "No changes to commit"
          git push